import type { Article, LocationData } from '@/lib/types';

export const locationData: LocationData = {
  India: {
    states: {
      'All India': [],
      'Andhra Pradesh': ['Amaravati', 'Visakhapatnam', 'Vijayawada'],
      'Maharashtra': ['Mumbai', 'Pune', 'Nagpur'],
      'Karnataka': ['Bengaluru', 'Mysuru', 'Mangaluru'],
      'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai'],
      'Delhi': ['New Delhi'],
      'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Agra'],
    },
  },
};

export const articles: Article[] = [
  {
    id: '1',
    title: 'ISRO successfully launches new communication satellite GSAT-20',
    titleHi: 'इसरो ने नए संचार उपग्रह जीसैट-20 का सफल प्रक्षेपण किया',
    summary: 'The Indian Space Research Organisation (ISRO) has achieved another milestone with the successful launch of its new communication satellite, GSAT-20.',
    summaryHi: 'भारतीय अंतरिक्ष अनुसंधान संगठन (इसरो) ने अपने नए संचार उपग्रह, जीसैट-20 के सफल प्रक्षेपण के साथ एक और मील का पत्थर हासिल किया है।',
    importantPoints: [
      'GSAT-20 is a high-throughput satellite aimed at providing high-speed internet connectivity.',
      'The launch was conducted from the Satish Dhawan Space Centre in Sriharikota.',
      'It will primarily serve remote and unconnected regions of India.',
    ],
    importantPointsHi: [
      'जीसैट-20 एक उच्च-थ्रूपुट उपग्रह है जिसका उद्देश्य उच्च गति की इंटरनेट कनेक्टिविटी प्रदान करना है।',
      'प्रक्षेपण श्रीहरिकोटा के सतीश धवन अंतरिक्ष केंद्र से किया गया।',
      'यह मुख्य रूप से भारत के दूरस्थ और असंबद्ध क्षेत्रों की सेवा करेगा।',
    ],
    contentUrl: '#',
    source: { name: 'The Hindu', cred_score: 0.9 },
    publishedAt: '2 hours ago',
    country: 'India',
    state: 'Andhra Pradesh',
    city: 'Sriharikota',
    category: 'Science',
    media: { image: 'https://picsum.photos/600/400' },
    rank_score: 95,
  },
  {
    id: '2',
    title: 'Global Economic Forum addresses climate change challenges',
    titleHi: 'वैश्विक आर्थिक मंच ने जलवायु परिवर्तन की चुनौतियों पर चर्चा की',
    summary: 'Leaders from around the world gathered to discuss urgent actions required to combat the growing threat of climate change.',
    summaryHi: 'दुनिया भर के नेता जलवायु परिवर्तन के बढ़ते खतरे से निपटने के लिए आवश्यक तत्काल कार्रवाइयों पर चर्चा करने के लिए एकत्रित हुए।',
    importantPoints: [
      'The forum emphasized the need for a transition to renewable energy sources.',
      'Carbon pricing and green investments were key topics of discussion.',
      'Developing nations called for more financial support from developed countries.',
    ],
    importantPointsHi: [
      'मंच ने नवीकरणीय ऊर्जा स्रोतों में संक्रमण की आवश्यकता पर जोर दिया।',
      'कार्बन मूल्य निर्धारण और हरित निवेश चर्चा के प्रमुख विषय थे।',
      'विकासशील देशों ने विकसित देशों से अधिक वित्तीय सहायता की मांग की।',
    ],
    contentUrl: '#',
    source: { name: 'Reuters', cred_score: 0.95 },
    publishedAt: '5 hours ago',
    country: 'World',
    state: null,
    city: null,
    category: 'Environment',
    media: { image: 'https://picsum.photos/600/401' },
    rank_score: 92,
  },
  {
    id: '3',
    title: 'New Policy for Digital India to Boost Startups',
    titleHi: 'स्टार्टअप को बढ़ावा देने के लिए डिजिटल इंडिया के लिए नई नीति',
    summary: 'The government has announced a new policy under the Digital India initiative to provide a conducive environment for technology startups.',
    summaryHi: 'सरकार ने प्रौद्योगिकी स्टार्टअप के लिए एक अनुकूल वातावरण प्रदान करने के लिए डिजिटल इंडिया पहल के तहत एक नई नीति की घोषणा की है।',
    importantPoints: [
      'The policy includes tax incentives and easier access to funding.',
      'A dedicated portal will be launched to streamline registration and compliance.',
      'Focus on fostering innovation in AI, blockchain, and IoT sectors.',
    ],
    importantPointsHi: [
      'नीति में कर प्रोत्साहन और धन तक आसान पहुंच शामिल है।',
      'पंजीकरण और अनुपालन को सुव्यवस्थित करने के लिए एक समर्पित पोर्टल लॉन्च किया जाएगा।',
      'एआई, ब्लॉकचेन और आईओटी क्षेत्रों में नवाचार को बढ़ावा देने पर ध्यान केंद्रित करें।',
    ],
    contentUrl: '#',
    source: { name: 'Press Information Bureau', cred_score: 0.85 },
    publishedAt: '1 day ago',
    country: 'India',
    state: 'Delhi',
    city: 'New Delhi',
    category: 'Politics',
    media: { image: 'https://picsum.photos/600/402' },
    rank_score: 88,
  },
  {
    id: '4',
    title: 'Breakthrough in Alzheimer\'s research offers new hope',
    titleHi: 'अल्जाइमर अनुसंधान में सफलता से नई उम्मीद जगी',
    summary: 'Scientists have identified a new protein that could be key to preventing and treating Alzheimer\'s disease.',
    summaryHi: 'वैज्ञानिकों ने एक नए प्रोटीन की पहचान की है जो अल्जाइमर रोग को रोकने और उसका इलाज करने में महत्वपूर्ण हो सकता है।',
    importantPoints: [
      'The research was published in the journal "Nature Medicine".',
      'Clinical trials for a new drug targeting this protein are expected to begin next year.',
      'This could lead to the first effective treatment for the neurodegenerative disease.',
    ],
    importantPointsHi: [
      'यह शोध "नेचर मेडिसिन" पत्रिका में प्रकाशित हुआ था।',
      'इस प्रोटीन को लक्षित करने वाली एक नई दवा के लिए नैदानिक परीक्षण अगले साल शुरू होने की उम्मीद है।',
      'यह न्यूरोडीजेनेरेटिव बीमारी के लिए पहला प्रभावी उपचार हो सकता है।',
    ],
    contentUrl: '#',
    source: { name: 'Science Daily', cred_score: 0.88 },
    publishedAt: '3 days ago',
    country: 'World',
    state: null,
    city: null,
    category: 'Science',
    media: { image: 'https://picsum.photos/600/403' },
    rank_score: 85,
  },
  {
    id: '5',
    title: 'RBI holds repo rate steady amid inflation concerns',
    titleHi: 'मुद्रास्फीति की चिंताओं के बीच आरबीआई ने रेपो दर को स्थिर रखा',
    summary: 'The Reserve Bank of India\'s Monetary Policy Committee has decided to keep the repo rate unchanged at 6.5% to control inflation.',
    summaryHi: 'भारतीय रिजर्व बैंक की मौद्रिक नीति समिति ने मुद्रास्फीति को नियंत्रित करने के लिए रेपो दर को 6.5% पर अपरिवर्तित रखने का निर्णय लिया है।',
    importantPoints: [
      'This is the fifth consecutive time the MPC has maintained the status quo.',
      'The decision aims to balance economic growth with inflation control.',
      'Future rate cuts will depend on the monsoon and global economic trends.',
    ],
    importantPointsHi: [
      'यह लगातार पांचवीं बार है जब एमपीसी ने यथास्थिति बनाए रखी है।',
      'निर्णय का उद्देश्य आर्थिक विकास को मुद्रास्फीति नियंत्रण के साथ संतुलित करना है।',
      'भविष्य में दरों में कटौती मानसून और वैश्विक आर्थिक रुझानों पर निर्भर करेगी।',
    ],
    contentUrl: '#',
    source: { name: 'The Economic Times', cred_score: 0.92 },
    publishedAt: '8 hours ago',
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
    category: 'Economy',
    media: { image: 'https://picsum.photos/600/404' },
    rank_score: 90,
  },
];
