
"use client";

import { useAudioPlayer } from '@/context/audio-player-context';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Pause, Play, X, Loader2 } from 'lucide-react';
import type { Language } from '@/lib/types';
import { useEffect, useRef, useState } from 'react';

export function AudioPlayer({ language }: { language: Language }) {
  const {
    article,
    isPlaying,
    isLoading,
    togglePlayPause,
    stop,
    mode,
    playlistTitle,
    playlistSubtitle,
    playlistAudioUri,
    isPlaylistPlaying,
    togglePlaylistPlayPause,
    audioUri,
  } = useAudioPlayer();
  
  const audioRef = useRef<HTMLAudioElement>(null);
  const [duration, setDuration] = useState(0);

  const currentAudioUri = mode === 'playlist' ? playlistAudioUri : audioUri;
  const currentIsPlaying = mode === 'playlist' ? isPlaylistPlaying : isPlaying;

  useEffect(() => {
    const audioElement = audioRef.current;
    if (audioElement) {
        const handleLoadedMetadata = () => setDuration(audioElement.duration);
        
        audioElement.addEventListener('loadedmetadata', handleLoadedMetadata);
        
        if(currentIsPlaying) {
          audioElement.play().catch(e => console.error("Audio play failed", e));
        } else {
          audioElement.pause();
        }

        return () => {
            audioElement.removeEventListener('loadedmetadata', handleLoadedMetadata);
        };
    }
  }, [currentAudioUri, currentIsPlaying]);

  const handleToggle = () => {
    if (mode === 'playlist') {
        togglePlaylistPlayPause();
    } else {
        togglePlayPause();
    }
  };
  
  const shouldShow = isLoading || currentAudioUri;

  if (!shouldShow) return null;
  
  let title, subtitle, infoText;
  
  if (isLoading) {
    title = article ? (language === 'hi' && article.titleHi ? article.titleHi : article.title) : 'Loading...';
    subtitle = 'Generating AI audio...';
    infoText = '(Audio generated by AI)';
  } else if (mode === 'playlist') {
    title = playlistTitle;
    subtitle = playlistSubtitle;
    infoText = '(Audio generated by AI)';
  } else {
    title = article ? (language === 'hi' && article.titleHi ? article.titleHi : article.title) : "Article";
    subtitle = article ? article.source.name : '';
    infoText = '(Audio generated by AI)';
  }

  return (
     <div className="fixed bottom-0 left-0 right-0 z-50 p-4 backdrop-blur-sm transition-transform duration-300 ease-in-out"
       style={{ transform: `translateY(${shouldShow ? '0%' : '100%'})` }}>
        <Card className="max-w-4xl mx-auto p-4 shadow-2xl bg-white/80 dark:bg-slate-800/80 border-slate-200 dark:border-slate-700">
          <div className="flex items-center gap-4">
            {currentAudioUri && <audio ref={audioRef} src={currentAudioUri} onEnded={stop} onPlay={() => mode === 'playlist' ? togglePlaylistPlayPause(true) : undefined} onPause={() => mode === 'playlist' ? togglePlaylistPlayPause(false) : undefined} />}
            <Button variant="ghost" size="icon" onClick={handleToggle} disabled={isLoading}>
              {isLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : currentIsPlaying ? <Pause className="h-6 w-6" /> : <Play className="h-6 w-6" />}
            </Button>
            <div className="flex-1 overflow-hidden">
              <p className="font-bold truncate font-headline">{title}</p>
              <p className="text-sm text-muted-foreground">{subtitle}</p>
               <div className="mt-2 text-xs text-muted-foreground">
                  {infoText}
               </div>
            </div>
            <Button variant="ghost" size="icon" onClick={stop}>
              <X className="h-6 w-6" />
              <span className="sr-only">Close Player</span>
            </Button>
          </div>
        </Card>
      </div>
  )
}

    